config/routes.rb
CukeCms::Application.routes.draw do

  resources :content_types do
    resources :contents
  end

  resources :contents

  root :to => 'content_types#index'

end

app/models/content.rb
class Content
  include Mongoid::Document

  referenced_in :content_type

  field :slug,            :type => String
  field :title,           :type => String
  field :body,            :type => String
end

app/models/content_type.rb
class ContentType
  include Mongoid::Document

  references_many :contents

  field :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/content_types_controller.rb
class ContentTypesController < ApplicationController
  def index
    @content_types = ContentType.all
  end

  def new
    @content_type = ContentType.new
  end
  
  def create
    @content_type = ContentType.new(params[:content_type])

    if @content_type.save
      redirect_to @content_type
    else
      render :new
    end
  end

  def update
    @content_type = ContentType.find(params[:id])
    @content_type.write_attributes(params[:content_type])

    if @content_type.save
      redirect_to @content_type
    else
      render :edit
    end
  end

  def show
    @content_type = ContentType.find(params[:id])
  end

  def edit
    @content_type = ContentType.find(params[:id])
  end

  def destroy
    @content_type = ContentType.find(params[:id])
    @content_type.destroy

    redirect_to content_types_path
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_filter :get_content_type

  def index
    @contents = Content.all
  end

  def new
    @content = Content.new
  end

  def create
    @content = Content.new(params[:content])

    if @content.save
      if @content_type
        @content_type.contents << @content
        redirect_to [@content_type, @content]
      else
        redirect_to @content
      end
    else
      render :new
    end
  end

  def update
    @content = Content.find(params[:id])
    @content.write_attributes(params[:content])

    if @content.save
      redirect_to @content
    else
      render :edit
    end
  end

  def edit
    @content = Content.find(params[:id])
  end

  def show
    @content = Content.find(params[:id])
  end

  def destroy
    @content = Content.find(params[:id])
    @content.destroy

    redirect_to contents_path
  end

  private
  def get_content_type
    @content_type = ContentType.find(params[:content_type_id]) if params[:content_type_id]
    @content_type = ContentType.find(params[:content][:content_type_id]) if params[:content] && params[:content][:content_type_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/content_types/_form.html.erb
<%= form_for content_type, :html => {:class => 'bp'} do |f| -%>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <button type="submit" class="button positive">
    <img src="/images/buttons/tick.png" alt=""/> Save
  </button>
<% end -%>

app/views/content_types/edit.html.erb
<h2>Edit Content Type: <%= @content_type.name %></h2>

<%= render :partial => 'form', :locals => { :content_type => @content_type } %>

app/views/content_types/index.html.erb
<h2>Manage Content Types</h2>
<div id="create_content_type" class="create_item">
  <%= link_to new_content_type_path, :class => 'button positive' do %>
    <!-- <%= image_tag '/images/buttons/tick.png' %>  -->Add New
  <% end %>
</div>

<div class="index_table">
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    <% @content_types.each do |content_type| %>
      <tr class="<%= cycle("even", "odd") -%>">
        <td class="name">
          <%= link_to content_type.name, content_type %>
        </td>
        <td class="actions">
          <%= link_to "Edit", edit_content_type_path(content_type), :class => 'admin icon edit' %>
          <%= link_to "Delete", content_type,
                      { :confirm => "Are you sure?",
                        :method => :delete,
                        :class => 'icon delete' } %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/content_types/new.html.erb
<h2>New Content Type</h2>
<%= render :partial => 'form', :locals => { :content_type => @content_type } %>

app/views/content_types/show.html.erb
<h2>Viewing: <%= @content_type.name.capitalize %></h2>

<div id="create_content">
  <%= link_to 'Add New Content', new_content_type_content_path(@content_type), :class => 'button positive' %>
</div>

<h3>Listing Content</h3>
<ul>
  <% @content_type.contents.each do |content| %>
    <li><%= link_to content.title, [@content_type, content] %></li>
  <% end %>
</ul>

app/views/contents/_form.html.erb
<% content_type ||= nil %>

<%= form_for [content_type, content].compact, :html => {:class => 'bp'} do |f| -%>
  <% if content.new_record? and not content_type %>
    <div>
      <%= f.label :content_type_id %>
      <%= f.collection_select :content_type_id, ContentType.all, :id, :name %>
    </div>
  <% end %>

  <div>
    <%= f.label :slug, "Slug" %>
    <%= f.text_field :slug %>
  </div>

  <div>
    <%= f.label :title, "Title" %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :body, "Body" %>
    <%= f.text_area :body %>
  </div>

  <button type="submit" class="button positive">
    <img src="/images/buttons/tick.png" alt=""/> Save
  </button>
<% end -%>

app/views/contents/edit.html.erb
<h2>Edit Content: <%= @content.title %></h2>

<%= render :partial => 'form', :locals => { :content => @content, :content_type => @content.content_type } %>

app/views/contents/index.html.erb
<h2>All Content</h2>
<div class="index_table">
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Slug</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @contents.each do |content| %>
      <tr class="<%= cycle("even", "odd") -%>">
        <td class="title">
          <%= link_to content.title, content %>
        </td>
        <td class="slug">
          <%= content.slug %>
        </td>
        <td class="actions">
          <%= link_to "Edit", edit_content_path(content), :class => 'icon edit' %>
          <%= link_to "Delete", content,
                      { :confirm => "Are you sure?",
                        :method => :delete,
                        :class => 'icon delete' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/contents/new.html.erb
<h2>New Content</h2>

<p>Fill in the values below to create a new piece of content</p>

<%= render :partial => 'form', :locals => { :content => @content, :content_type => @content_type } %>

app/views/contents/show.html.erb
<h2><%= @content.title %></h2>

<ul>
  <li>Slug: <%= @content.slug %></li>
  <li>Title: <%= @content.title %></li>
  <li>Body: <%= @content.body %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <title>cukes CMS</title>

  <%= stylesheet_link_tag 'compiled/screen.css', :media => 'screen, projection' %>
  <!-- [if lt IE 8]>
    <%= stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection' %>
  <![endif] -->
  <!--[if lt IE 7]>
    <%= stylesheet_link_tag 'compiled/ie6.css', :media => 'screen, projection' %>
  <[endif] -->

  <%= javascript_include_tag :defaults %>

  <%= csrf_meta_tag %>
</head>
<body class="admin">
  <div class="wrapper">
    <div class="container">
      <div id="header">
        <div id="logo">
          <h1 id="sitename">cukes CMS</h1>
          <p id="tagline">Well behaved content management</p>
        </div>

        <div id="nav">
          <%= render_navigation :expand_all => true %>
        </div>
      </div>
      <div id="main">
        <div id="breadcrumbs">
          <%= render_navigation :renderer => :breadcrumbs, :join_with => " &gt; " %>
        </div>
        <div id="content">
          <%= yield %>
        </div>
        <div id="sidebar">
          <div id="subnav">
            <h3><%= active_navigation_item_name :level => 1 %></h3>
            <%= render_navigation :level => 2 %>
          </div>
        </div>
      </div>
      <div id="footer">
      </div>
    </div>
  </div>
</body>
</html>